### PR TITLE
FIxed a bug

### PR DESCRIPTION
**Pull request by Papsanly**
It scrolls to bottom when not needed, i fixed it

### CODE REVIEW

**Comment by SophiWeiss** [comment]
u r so talented, my lovely boy!

**Comment by Papsanly** [comment]
not more then u)

**Comment by SophiWeiss** [comment]
mgh mgh

**Comment by SophiWeiss** [comment]
love u!)

**Comment by Papsanly** [comment]
love u too

**Comment by Papsanly** [comment]
merge it pls))

**Review by SophiWeiss — APPROVED** [review]
NYA NYA NYA NYA

**Comment by karman-ly** [comment]
Hello guys, u r strange...

**Pull request merged**
