### PR TITLE
Added storage

### PR DESCRIPTION
**Pull request by Papsanly**
I used AsyncStorage library to implement long term storage for todos data

### CODE REVIEW

**Comment by SophiWeiss** [comment]
U R SO WONDERFUL!! BOIIIFRIEND OF MY WET DREAMS!

**Comment by Papsanly** [comment]
cool

**Comment by Papsanly** [comment]
Kidding)) LOVE U TOO MY FAVOURITE GF!

**Comment by SophiWeiss** [comment]
NYAMOVIIIIIIIIIIIIIIIIIIIII

**Review by SophiWeiss — APPROVED** [review]
It  `s so cool

**Pull request merged**
